modLoader = "kotlinforforge" #mandatory
loaderVersion = "[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
[[mods]] #mandatory
    modId = "hollowengine" #mandatory
    version = "${file.jarVersion}" #mandatory
    displayName = "Hollow Engine" #mandatory
    description = ''''''

[[dependencies.hollowengine]] #optional
    modId = "forge" #mandatory
    mandatory = true #mandatory
    versionRange = "[36,)" #mandatory
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hollowengine]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hollowengine]]
    modId = "hc"
    mandatory = true
    versionRange = "[1.1.0,2.0)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.hollowengine]]
    modId = "kotlinforforge"
    mandatory = true
    versionRange = "[3.10.0,4.0.0)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.hollowengine]]
modId = "ftbteams"
mandatory = true
versionRange = "[1802.2.11,)"
ordering = "AFTER"
side = "BOTH"
