modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "ZDsDCM"
[[mods]] #mandatory
modId = "hollowengine" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Hollow Engine" #mandatory
description = '''
'''

[[dependencies.hollowengine]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "hc"
mandatory = true
versionRange = "[1.1.0,2.0)"
ordering = "NONE"
side = "BOTH"
